### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by resom78** [Magisk-Modules-Repo/gjf_bt#1]
I have installed the module through Magisk manager but it doesn't change anything to the bluetooth codec: In developper option I can't select dual channel and I don't hear any difference even if I choose 800kbit/s.
How to be sure the patch is applyied?
I have a Unihertz Jelly Pro with stock ROM.

Anyway thanks for effort!

**Comment by gjf** [comment]
Unihertz Jelly Pro can use Android 7 and Android 8. So what is Android version on your phone?
Also please note the module breaks ROM ability to change codec settings in developer options.
It means it will be ALWAYS Dual Channel and ALWAYS with bit rate you have chosen when installed the module.
In fact, the quality of the sound is mainly based on source qualtiy and quality of headphones. To check does this module works you need to provide Bluetooth HCI log that is possible to get in developer options.
