### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by resom78** [Magisk-Modules-Repo/gjf_bt#3]
Hi,

On my Cyrus CS28 android 7 when I try to install the module via Magisk, at the time I am supposed to select the bitrate, the module detects I am pressing a vol key even if it's not the case! Therefore on the screen it never stop changing the bitrate and I can't stop it! The only way is to reboot the phone.
I hope you understand what I am trying to explain!

Regards

**Comment by gjf** [comment]
Hi.
Sorry, but I cannot reproduce this problem. Probably it is for your device only.

**Comment by resom78** [comment]
Hi,
Thanks for your answer!In fact I tried on another device: Geotel G1 under android 7 and the result is the same!
Regards
    Le vendredi 3 mai 2019 à 16:33:00 UTC+2, gjf <notifications@github.com> a écrit :  
 
 
Hi.
Sorry, but I cannot reproduce this problem. Probably it is for your device only.

**Comment by gjf** [comment]
I am testing it right now on Xiaomi Redmi 4s and Xiaomi Redmi 5 Plus - everything works properly both during installation and after reboot.

**Comment by iorazbek** [comment]
Getting the same issue on Moto E4 running Nougat. 

![20190519_Screenshot_20190519-193203](https://user-images.githubusercontent.com/5728319/57985161-dc7e1400-7a85-11e9-9fe5-f57e255f3555.png)

**Comment by resom78** [comment]
Hi,

I think this issue is related to android 7, do you think you can do something to fix it?

Regards

**Comment by Acters** [comment]
Sorry but I'm on a LG V30 on Oreo(8.0). same issue

**Comment by JustACatRu** [comment]
Have the same issue on Xiaomi Mi Mix (android 7.0, miui 9.5.1.0).
But I'm able to install it 50/50. I mean, sometimes it works, and sometimes just starting to go crazy like on **iorazbek** screenshot, then I have to kill Magisk Manager and repeat installation.

**Comment by glazunoff** [comment]
Have the same issue on Xiaomi Pocophone F1 (android 9.0, miui 10.3.5.0).

**Comment by gjf** [comment]
The problem is caused by keycheck routine that I cannot change.
I will release a separate module without possibility to choose bitrate with constant most stable value 454 rbit/s that works in most cases. Will let you know later.

**Comment by gjf** [comment]
Sorry, guys, no solution. The reason is stated here: https://github.com/Magisk-Modules-Repo/submission/issues/461

**Comment by White-Tiger** [comment]
here's a fix:
```patch
diff --git "a/install.sh" "b/install.sh"
index 8b5c05c..73aa1bd 100644
--- "a/install.sh"
+++ "b/install.sh"
@@ -138,6 +138,17 @@ on_install() {
   # Extend/change the logic to whatever you want
   ui_print "- Extracting module files"
   unzip -o "$ZIPFILE" 'system/*' -d $MODPATH >&2
+
+  if [ "$ARCH32" == "arm" ]; then
+    KEYCHECK=keycheck-arm
+  else
+    KEYCHECK=keycheck-x86
+  fi
+  # Keycheck binary by someone755 @Github
+  unzip -o "$ZIPFILE" 'common/$KEYCHECK' -d $TMPDIR
+  KEYCHECK="$TMPDIR/$KEYCHECK"
+  chmod 0755 $KEYCHECK
+
   #Place for check functions
   osver_fn
   #Let's ask which bitrate is needed
@@ -190,9 +201,9 @@ chooseportold() {
   $KEYCHECK
   $KEYCHECK
   SEL=$?
-  if [ "$1" == "UP" ]; then
+  if [ "$1" = "UP" ]; then
     UP=$SEL
-  elif [ "$1" == "DOWN" ]; then
+  elif [ "$1" = "DOWN" ]; then
     DOWN=$SEL
   elif [ $SEL -eq $UP ]; then
     return 1
@@ -205,14 +216,6 @@ chooseportold() {
 }
 
 choosebitrate() {
-  # Keycheck binary by someone755 @Github, idea for code below by Zappo @xda-developers
-  if "$ARCH32" == "arm"; then
-	KEYCHECK=$TMPDIR/common/keycheck-arm
-		else
-			KEYCHECK=$TMPDIR/common/keycheck-x86
-  fi
-  chmod 755 $KEYCHECK
-
   if keytest; then
     FUNCTION=chooseport
   else
@@ -225,11 +228,17 @@ choosebitrate() {
     $FUNCTION "DOWN"
   fi
     BITRATE=0
+    LOOP=0
 	while [ $BITRATE -eq 0 ]; do
 		ui_print " "
-		ui_print " - Select Bitrate for SBC codec -"
+		ui_print " - Select Bitrate for SBC codec - ($LOOP)"
 		ui_print "   Choose which bitrate you want to install:"
 		ui_print "   Vol- = 454 kbit/s (works in most cases), Vol+ = higher"
+		if [ $LOOP -eq 10 ]; then
+			BITRATE=454
+			break
+		fi
+		$((++LOOP))
 		if $FUNCTION; then BITRATE=454
 			else 
 				ui_print " "
@@ -270,6 +279,6 @@ SDK_VER=23
   fi
 # Abort if no match
 if [ $DEVFND == 0 ]; then
-  abort "Android is older then Android 6 or modified build.prop! Aborting."
+  abort "Android is older than Android 6 or modified build.prop! Aborting."
 fi
 }
\ No newline at end of file
```

Basically key inputs using `keycheck` never worked. It's not device dependent _(that it unless the other method is available)_
**Reasons**: An `if` was wrongly used, resulting in always trying to use x86 `keycheck` files even on ARM, `keycheck` files were never actually extracted and simply didn't exist...

I've also added a pre-caution so that endless loops won't happen again. Basically if someone couldn't decide by his 10th iteration, it'll just use the default.

**Comment by gjf** [comment]
Implemented, thanks for a fix!

**Comment by Kein** [comment]
Which system files should I backup in case of bootlop for manual restoration later? I have TWRP.

**Comment by gjf** [comment]
> Which system files should I backup in case of bootlop for manual restoration later? I have TWRP.

None. Simply delete the module. Enjoy the world of Magisk ;)

**Comment by Acters** [comment]
> Which system files should I backup in case of bootlop for manual restoration later? I have TWRP.

This fix of issue isn't meant for bootlooped devices. This thread is meant for an infinite loop in the module installing process which should be fixed. you can always run a restore on the magisk files that control which modules to load up. good-luck!

**Comment by Kein** [comment]
> None. Simply delete the module. Enjoy the world of Magisk ;)

That's very odd, reading replies on XDA and 4PDA and there is a lot of people who got bootloop or bluetooth broken even after uninstalling module.
I dont mind manual restoration, just want to know what to restore
