### ISSUE TITLE
Using this module disables media audio on speaker or via headphone jack

### ISSUE THREAD

**Issue by JustACatRu** [Magisk-Modules-Repo/gjf_bt#5]
When I use this module, audio stops working on phones' speaker or via headphones jack.
But it affects only media audio (from music players or from video players (youtube for ex.)).
Also in this situation video plays buggy (it freezes and twitches).
But phone calls ringer melody, alarm or messages events keep working ok.
Sound over bluetooth works good too (including media). And video stops twitching when I connect bluetooth headphones.
My system is: Xiaomi Mi Mix (android 7.0, miui 9.5.1.0).
Is there any way I can troubleshoot this?
Thanks.

**Comment by gjf** [comment]
No idea what is wrong. Try to use lower bitrate, otherwise uninstall the module.
