### ISSUE TITLE
Unsure if it's working

### ISSUE THREAD

**Issue by skittles9823** [Magisk-Modules-Repo/gjf_bt#8]
Hi, I've been trying to get SBC XQ to work and short of flashing LOS this is the next best thing.

I'm using stock on my Pixel 3a XL but as far as I can tell there is no way to actually verify if this works? I've checked `dumpsys media.audio_flinger` and `dumpsys bluetooth_manager` as well as Bluetooth settings and developer options, but as far as I can tell nothing specifically shows what bitrate I'm processing at.

Just curious on what exactly you use to test if the module is working so I can verify myself.

**Comment by gjf** [comment]
Try to use Wireshark to check BT logs (they should be enabled in Developer Settings).
It should contain the profile that used to communicate with headsets.
There is a lot of information in Google how to do it.
