### ISSUE TITLE
Breaks bluetooth entirely on VNS-L21

### ISSUE THREAD

**Issue by marek26340** [Magisk-Modules-Repo/gjf_bt#9]
Hi, after installing this mod on Magisk 20.3 that is on my VNS-L21 which is running Android 7 (C432B504), bluetooth won't even turn on. Not like it's stuck while turning on, but... I tap on the bluetooth toggle, it goes gray as it should be turning on BT, but it will not turn on. And I'm able to try to turn it on again if I relaunch the Settings app. ---checking logs, I will add details if I will find something---

**Comment by gjf** [comment]
It means the module does not work with your device/firmware. Too bad - it cannot be fixed.
